apiVersion: v1
kind: Pod
metadata:
  name: dbpod
spec:
  volumes:
  - name: dpsecret
    secret:
      secretName: dbcreds
  containers:
  - image: nginx:1.19.0
    name: dbapp
    volumeMounts:
    - name: dpsecret
      mountPath: /var/app
